GET http://localhost:2000/

###
POST http://localhost:2000/api

###
GET http://localhost:2000/api/user

###
GET http://localhost:2000/api/user/x

###
POST http://localhost:2000/api/user
Content-Type: application/json

{
    "name": "Anthony",
    "lastName": "Luzquiños",
    "email": "v"
}

###
DELETE http://localhost:2000/api/user/6y52rZz6Ga1tqQkORfxQi

###
PATCH http://localhost:2000/api/user/dY25pFoos25qlhPqitz47
Content-Type: application/json

{
    "email": "c.parra@gmail.com"
}

###
POST http://localhost:2000/api/url/
Content-Type: application/json

{
    "link": "https://www.google.com/"
}

### 404 error
GET http://localhost:2000/route/that/does/not/exists

###
POST http://localhost:2000/api/user/signup
Content-Type: application/json

{
    "name": "valentina",
    "lastName": "reinoso",
    "email": "valentina.reinoso.rios@gmail.com",
    "password": "12345678"
}
